{% set name = "nomad-lab" %}
{% set version = "1.3.17" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2651fe88c988d9437be4f3e74b9987bfbc48c375f063242ba6a3d8826ebde9df

build:
  entry_points:
    - nomad = nomad.cli:run_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - aniso8601 >=7.0.0
    - ase >=3.22.0,<3.23.dev0
    - bitarray >=2.3.5
    - cachetools >=4.2.4
    - click >=7.1.2
    - docstring_parser >=0.12
    - elasticsearch-dsl ==7.4.0
    - h5py >=3.6.0
    - hjson-py >=3.0.2
    - httpx >=0.23.3,<0.28
    - importlib-metadata >=7.1.0,<7.2.dev0
    - jmespath >=0.10.0
    - python-kaleido ==0.2.1
    - lxml-html-clean >=0.1.0
    - lxml >=5.2
    - matid >=2.1.3
    - nptyping >=1.4.4,<1.5.dev0
    - numpy >=1.22.4,<2.0.0
    - openpyxl >=3.0.0
    - orjson >=1.0
    - pandas >=2.0.0
    - panedr >=0.2
    - parmed >=3.0.0
    - pint ==0.17
    - py-spy
    - pydantic >=2.0.0
    - pyinstrument
    - pymatgen >=2023.5.10
    - python-keycloak >=0.26.1
    - python-magic ==0.4.24
    - pytz >=2022.7.1
    - pyyaml >=6.0
    - requests >=2.27.1,<2.32.0
    - rfc3161ng >=2.1.3
    - scikit-learn >=1.0.2
    - scipy >=1.7.1
    - toposort >=1.0
    - typing_extensions >=4.12
    - unidecode ==1.3.2
    - wrapt >=1.12.1
    - xarray >=0.20.2
    - plotly <6.0.0

test:
  imports:
    - nomad
  commands:
    # - pip check
  requires:
    # - pip
    - python {{ python_min }}

about:
  home: https://nomad-lab.eu/
  license: Apache-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: The NOvel MAterials Discovery (NOMAD) Python package
  description: |
    This project implements the new nomad@FAIRDI infrastructure. Contrary
    to its NOMAD CoE predecessor, it implements the NOMAD Repository and
    NOMAD Archive functionality within a single cohesive application. 
    This project provides all necessary artifacts to develop, test, 
    deploy, and operate the NOMAD Respository and Archive.
  doc_url: https://nomad-lab.eu/prod/rae/docs/index.html
  dev_url: https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR

extra:
  recipe-maintainers:
    - jan-janssen
