{% set name = "nomad-lab" %}
{% set version = "1.4.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5868a735ed9a328c1ce3b8e7a4a83b601323a20eda685de317456387df83f19e
  patches:
    - pyspy.patch

build:
  entry_points:
    - nomad = nomad.cli:run_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - ase >=3.25.0
    - bitarray >=2.3.5
    - cachetools >=4.2.4
    - click >=7.1.2
    - docstring_parser >=0.12
    - elasticsearch-dsl >=7,<8
    - h5py >=3.6.0
    - httpx >=0.23.3,<0.28
    - jmespath >=0.10.0
    - jsonpath-ng
    - python-kaleido <=0.2.1
    - lxml >=5.2
    - matid >=2.1.3
    - msgpack-python >=1
    - msgspec
    - numpy >=1.22.4,<2
    - openpyxl
    - orjson >=1.0
    - pandas >=2
    - pint >=0.23
    - plotly <6
    - py-spy
    - pydantic >=2
    - pyinstrument
    - pymatgen >=2023.5.10
    - python-keycloak >=0.26.1
    - python-magic
    - pytz >=2022.7.1
    - pyyaml >=6.0
    - requests >=2.27.1,<2.32.0
    - rfc3161ng >=2.1.3
    - scipy >=1.7.1
    - unidecode
    - xarray >=0.20.2

test:
  imports:
    - nomad
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://nomad-lab.eu/
  license: Apache-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: The NOvel MAterials Discovery (NOMAD) Python package
  description: |
    This project implements the new nomad@FAIRDI infrastructure. Contrary
    to its NOMAD CoE predecessor, it implements the NOMAD Repository and
    NOMAD Archive functionality within a single cohesive application. 
    This project provides all necessary artifacts to develop, test, 
    deploy, and operate the NOMAD Respository and Archive.
  doc_url: https://nomad-lab.eu/prod/rae/docs/index.html
  dev_url: https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR

extra:
  recipe-maintainers:
    - jan-janssen
