{% set name = "nomad-lab" %}
{% set version = "1.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nomad-lab-{{ version }}.tar.gz
  sha256: 2abaea8c1991cb2fe658acd8048ac882edd32c2fb9c558a0d7f1f243752e85c3

build:
  number: 1
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - fastentrypoints
    - numpy
    - pip
    - pyyaml
    - setuptools
    - wheel
  run:
    - aniso8601 <=7
    - ase ==3.19.0
    - bravado
    - cachetools
    - click
    - cython >=0.19
    - docstring_parser
    - elasticsearch-dsl
    - fastentrypoints
    - future
    - jmespath
    - lxml
    - nptyping
    - orjson
    - pint
    - pip
    - pydantic
    - python
    - python-keycloak
    - pytz
    - pyyaml
    - requests
    - wheel
    - ecdsa
    - pyasn1
    - rsa
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - nomad

about:
  home: https://nomad-lab.eu/
  license: Apache-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: The NOvel MAterials Discovery (NOMAD) Python package
  description: |
    This project implements the new nomad@FAIRDI infrastructure. Contrary
    to its NOMAD CoE predecessor, it implements the NOMAD Repository and
    NOMAD Archive functionality within a single cohesive application. 
    This project provides all necessary artifacts to develop, test, 
    deploy, and operate the NOMAD Respository and Archive.
  doc_url: https://nomad-lab.eu/prod/rae/docs/index.html
  dev_url: https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR

extra:
  recipe-maintainers:
    - jan-janssen
