{% set name = "nomad-lab" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nomad-lab-{{ version }}.tar.gz
  sha256: d1f7747acc4061c280d025d723571342bcd13194744b8bca12daaeeda13c6272

build:
  entry_points:
    - nomad = nomad.cli:run_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - nptyping ==1.4.4
    - cachetools ==4.2.4
    - docstring_parser ==0.12
    - pint ==0.17
    - orjson ==3.6.0
    - click >=7.1.2
    - requests ==2.28.2
    - pytz ==2022.7.1
    - aniso8601 ==7.0.0
    - ase ==3.19.0
    - python-keycloak ==0.26.1
    - elasticsearch-dsl ==7.4.0
    - pydantic ==1.10.5
    - jmespath ==0.10.0
    - h5grove >=1.0.0
    - httpx ==0.23.3
    - memoization ==0.4.0
    - rfc3161ng ==2.1.3
    - lxml >=4.6,<5.dev0
    - wrapt >=1.12.1,<1.13.dev0
    - pyyaml ==6.0

test:
  imports:
    - nomad
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://nomad-lab.eu/
  license: Apache-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: The NOvel MAterials Discovery (NOMAD) Python package
  description: |
    This project implements the new nomad@FAIRDI infrastructure. Contrary
    to its NOMAD CoE predecessor, it implements the NOMAD Repository and
    NOMAD Archive functionality within a single cohesive application. 
    This project provides all necessary artifacts to develop, test, 
    deploy, and operate the NOMAD Respository and Archive.
  doc_url: https://nomad-lab.eu/prod/rae/docs/index.html
  dev_url: https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR

extra:
  recipe-maintainers:
    - jan-janssen
